pipeline {
    agent any
    options { 
        disableConcurrentBuilds() 
        buildDiscarder(logRotator(numToKeepStr: '30'))
    }
    stages {
        stage('set description') {
            steps {
                script {
                    currentBuild.description = sh(script: 'git log -1 --pretty=%B', returnStdout: true)
                }
            }
        }
        stage('build') {
            steps {
                script  {
                    sh """
                        cd jenkins_ec2/app
                        npm ci
                        npm run build
                    """
                }
            }
        }
        stage('cdk') {
            steps {
                script  {
                    sh """
                        cd jenkins_ec2/deploy
                        npm ci
                        npx cdk bootstrap
                        npx cdk deploy --require-approval never
                    """
                }
            }
        }
    }
}